services:
  mysql:
    image: mysql:8.0
    container_name: skillruta-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: skillruta
      MYSQL_USER: skilluser
      MYSQL_PASSWORD: skillpass
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer:4
    container_name: skillruta-adminer
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - '8080:8080'

volumes:
  mysql_data:
